### ISSUE TITLE
Don't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by kaster1980** [hrmuwanika/HLS-Streaming-Server#1]
Good day. Thank you so much for the script. Yesterday everything was running on Ubuntu 20.04 (there was only a problem with installing the ssl certificate), today you seem to have made edits and nothing works. Tell me how to start? Thanks in advance.

**Comment by hrmuwanika** [comment]
Hey its corrected now. i forget to edit the port 8080 to port 443. but it works now.

i will correct the ssl certificate later
